export const PROFILE_USER = "PROFILE_USER"
export const PROFILE_USER_REQUEST = "PROFILE_USER_REQUEST"

export const RECENTLY_TRACK_REQUEST = "RECENTLY_TRACK_REQUEST"
export const RECENTLY_TRACK = "RECENTLY_TRACK"

export const FEATURES_FOR_TRACK_REQUEST = "FEATURES_FOR_TRACK_REQUEST"
export const FEATURES_FOR_TRACK = "FEATURES_FOR_TRACK"

export const RECOMMENDATIONS_REQUEST = "RECOMMENDATIONS_REQUEST"
export const RECOMMENDATIONS = "RECOMMENDATIONS"

export const NEW_RELEASES_REQUEST = "NEW_RELEASES_REQUEST"
export const NEW_RELEASES = "NEW_RELEASES"

export const USER_PLAYLIST_REQUEST = "USER_PLAYLIST_REQUEST"
export const USER_PLAYLIST = "USER_PLAYLIST"

export const CATEGORIES_REQUEST = "CATEGORIES_REQUEST"
export const CATEGORIES = "CATEGORIES"

export const SEARCH_TRACKS_REQUEST = "SEARCH_TRACKS_REQUEST"
export const SEARCH_TRACKS = "SEARCH_TRACKS"